### ISSUE TITLE
Point-free style functions get their arguments only partially restored. 

### ISSUE THREAD

**Issue by tkerber** [omelkonian/agda2rust#2]
I noticed this when just aliasing functions:

```agda
data Foo : Set where
  foo : ℕ → Foo

f : ℕ → Foo
f = foo

g : ℕ → ℕ
g = suc

h : ℕ → ℕ
h = g
```
=>
```rust
pub enum Foo {
  foo(i32),
}

pub fn f(x0: i32) -> Far {
  Foo::foo()
}

pub fn g(x0: i32) -> i32 {
  1 + x0
}

pub fn h(x0: i32) -> i32 {
  g()
}
```

Note that the builtin constructor seems to behave fine, but the function call and non-builtin constructor are missing the argument `x0`.

**Comment by omelkonian** [comment]
Yes I'm aware partial application / currying / etc. is currently broken, and I'm working on it. 

The reason builtin suc/addition works is that I've added an ad-hoc part of the codebase that handles just that so that I can write interesting examples until I have the full working functionality: https://github.com/omelkonian/agda2rust/blob/master/src/Agda2Rust/Convert/Terms.hs#L41-L43
